const actions = {
    ADD_COMPONENT: "ADD_COMPONENT",
    REMOVE_COMPONENT: "REMOVE_COMPONENT",
    UPDATE_COMPONENTS: "UPDATE_COMPONENTS",
    MAKE_FIRST_ROUND: "MAKE_FIRST_ROUND"
}

export default actions;